### ISSUE TITLE
hide calendar name, new arguments

### ISSUE THREAD

**Issue by amitkalani1** [mogproject/calendar-cli#13]
I'd like arguments to hide stuff like the calendar name, and arguments to add stuff like appointment location which is saved in google calendar for an event.

**Comment by mogproject** [comment]
I will introduce `--format` argument so that you can arrange the text format to be printed.

**Comment by mogproject** [comment]
`--format` and `--location` options are now available in version 0.2.0.
https://github.com/mogproject/calendar-cli/blob/master/src/calendar_cli/setting/arg_parser.py#L52-L66
