### ISSUE TITLE
show events from the next X days

### ISSUE THREAD

**Issue by amitkalani1** [mogproject/calendar-cli#15]
I'd like to give calendar-cli and argument like --days 7 or --days 3

so it will give me my appointments for the week or set days

**Comment by amitkalani1** [comment]
or add arguments like today, tomorrow, tomorrow+1, so you can pick a specific date without naming the exact date

**Comment by mogproject** [comment]
Released v0.2.1, which has been Implemented `--days` option .
Please upgrade and see the command help (`calendar-cli -h`).

**Comment by amitkalani1** [comment]
works like a charm, is it possible to get a seperator between days though?

like

day1
~ ~ ~ ~
day2

**Comment by mogproject** [comment]
Thanks. I think I can add `--separator` option.

**Comment by mogproject** [comment]
Implemented #18
