### ISSUE TITLE
Naming conflict with https://github.com/tobixen/calendar-cli

### ISSUE THREAD

**Issue by tobixen** [mogproject/calendar-cli#20]
Ref https://github.com/tobixen/calendar-cli/issues/24

I never bothered registering my calendar-cli with pypi, because it's supposed to be a command-line tool and not a python library.  Anyway, according to the bug report people are actually having problems due to the naming conflict.

I would ask if it's possible to rename this calendar-cli to gcalendar-cli.  After all it's locked to the google calendar backend if I've understood it correct, and it's also some years older than "my" calendar-cli

**Comment by mogproject** [comment]
Thanks for telling me that. I understood the situation and will rename my pypi project.

**Comment by mogproject** [comment]
Renamed.
